KEEP_ALIVE = 60
QUEUE_LENGTH = 5  # Balanced target concurrency
RECONCILE_INTERVAL=1
REACTIVE_RECONCILE_INTERVAL=5
PROACTIVE_RECONCILE_INTERVAL=15
PREDICTION_WINDOW_SIZE=60
PREPARE_PREDICTION_WINDOW_SIZE=5
