_wandb:
    value:
        cli_version: 0.22.1
        e:
            mp4vycy8mha1fynh6zo97hz5wf47b9ai:
                codePath: src/notebooks/new/gnn_v4.ipynb
                codePathLocal: gnn_v4.ipynb
                cpu_count: 16
                cpu_count_logical: 16
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "211044827136"
                        used: "50882519040"
                email: nikolalukic167@gmail.com
                executable: /root/.local/share/virtualenvs/my-herosim-7iPRbgpb/bin/python
                git:
                    commit: 96427114222b61981cb848078e8e59c9f8c84a99
                    remote: https://git.dsg.tuwien.ac.at/praith/my-herosim.git
                gpu: Tesla T4
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2560
                      memoryTotal: "16106127360"
                      name: Tesla T4
                      uuid: GPU-c9bee304-1e67-b007-a5e4-21ad82475308
                host: mitrix
                memory:
                    total: "33652129792"
                os: Linux-6.8.0-85-generic-x86_64-with-glibc2.39
                program: /root/projects/my-herosim/src/notebooks/new/gnn_v4.ipynb
                python: CPython 3.12.3
                root: /root/projects/my-herosim/src/notebooks/new
                startedAt: "2025-10-20T13:08:09.045308Z"
                writerId: mp4vycy8mha1fynh6zo97hz5wf47b9ai
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 5
                - 53
                - 77
            "2":
                - 1
                - 5
                - 53
                - 77
            "3":
                - 1
                - 2
                - 16
                - 61
                - 62
            "4": 3.12.3
            "5": 0.22.1
            "8":
                - 1
            "12": 0.22.1
            "13": linux-x86_64
device:
    value: cuda
embedding_dim:
    value: 64
epochs:
    value: 50
hidden_dim:
    value: 128
lr:
    value: 0.001
