_wandb:
    value:
        cli_version: 0.22.1
        e:
            7s5ucnvs8vs0dg6nmq9051wubkk4si46:
                codePath: src/notebooks/new_new/14-12-17-52.py
                codePathLocal: 14-12-17-52.py
                cpu_count: 16
                cpu_count_logical: 16
                disk:
                    /:
                        total: "211044827136"
                        used: "123572215808"
                email: nikolalukic167@gmail.com
                executable: /root/.local/share/virtualenvs/my-herosim-7iPRbgpb/bin/python3
                git:
                    commit: b5169cff0bbb037e2039eac7e231cfb0e3201c70
                host: mitrix
                memory:
                    total: "33652129792"
                os: Linux-6.8.0-85-generic-x86_64-with-glibc2.39
                program: /root/projects/my-herosim/src/notebooks/new_new/14-12-17-52.py
                python: CPython 3.12.3
                root: /root/projects/my-herosim/src/notebooks/new_new
                startedAt: "2025-12-14T20:31:03.354509Z"
                writerId: 7s5ucnvs8vs0dg6nmq9051wubkk4si46
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 5
                - 53
                - 77
            "2":
                - 1
                - 5
                - 53
                - 77
            "3":
                - 1
                - 16
                - 61
            "4": 3.12.3
            "5": 0.22.1
            "12": 0.22.1
            "13": linux-x86_64
device:
    value: cuda
embedding_dim:
    value: 64
epochs:
    value: 200
hidden_dim:
    value: 64
lr:
    value: 0.001
